imports: # read in order
  - ./general/NEWA_Kassel_general_dataset.yaml
  - ./instruments/WLS70_general_instrument_description.yaml
  - ./processing/NEWA_Kassel_data_processing_history.yaml

attributes:

  # specific device description
  serial_number: ''
  specific_lidar_name: 'Alize'
  specific_lidar_owner: 'DTU Wind'
  specific_lidar_operator: 'DTU Wind'
  instrument_comment: 'The installation site ID of this instrument is WP6, compare experiment documentation report. It was installed close to the 140m mast southwest of Roedeser Berg.'
  
  # specific measurement configuration
  n_gates_vary: 'false'
  spatial_averaging_info: ''
  beam_sweeping: 'false'
  measurement_scenario: 'DBS'
  n_lidars: '0'
  linked_lidars: 'not applicable'
  configuration_comment: ''

  accumulation_time: 1
  

  
variables:
  yaw:
    data_type: 'f4' #f4 = float (f8 = double)
    units: 'degrees'
    long_name: 'lidar_yaw_angle'
    comment: 'The home position of the lidar has been configured in a way that 0 azimuth corresponds to north.'
    accuracy: ''
    accuracy_info: 'No information on yaw accuracy available.'
    value: 0

  pitch:
    data_type: 'f4'
    units: 'degrees'
    long_name: 'lidar_pitch_angle'
    comment: ''
    accuracy: ''
    accuracy_info: 'No information on pitch accuracy available.'
    value: 0

  roll:
    data_type: 'f4'
    units: 'degrees'
    long_name: 'lidar_roll_angle'
    comment: ''
    accuracy: ''
    accuracy_info: 'No information on roll accuracy available.'
    value: 0

  scan_id:
    data_type: 'i' #i = integer
    units: 'none'
    long_name: 'scan_id_of_the_measurement'
    value: 1
    
  position_x:
    data_type: 'f4'
    units: 'degrees east'
    long_name: 'x_position_of_lidar'
    value: 511642
    
  position_y:
    data_type: 'f4'
    units: 'degrees north'
    long_name: 'y_position_of_lidar'
    value: 5687589

  position_z:
    data_type: 'f4'
    units: 'meters'
    long_name: 'z_position_of_lidar'
    value: 260.8

parameters:
  output_block_size: # accepts positive values and <nothing> (in the latter case, produces only one output file)
  input:
    path: ..\data\WP6\
    format: WLS70
  output:
    path: .\converted
    format: NetCDF4