imports: # read in order
  - ./general/NEWA_Kassel_general_dataset.yaml
  - ./instruments/AQ500_general_instrument_description.yaml
  - ./processing/NEWA_Kassel_data_processing_history.yaml

attributes:

  # specific device description
  serial_number: 'AJ03'
  specific_lidar_name: ''
  specific_lidar_owner: 'anemos-jacob GmbH'
  specific_lidar_operator: 'anemos-jacob GmbH'
  instrument_comment: 'The installation site ID of this instrument is WP5, compare experiment documentation report. It was installed north-east of WP1.'

  # specific measurement configuration
  configuration_comment: ''

  
variables:   
  position_x:
    data_type: 'f4'
    units: 'degrees east'
    long_name: 'x_position_of_lidar'
    value: 516522

  position_y:
    data_type: 'f4'
    units: 'degrees north'
    long_name: 'y_position_of_lidar'
    value: 5694134

  position_z:
    data_type: 'f4'
    units: 'meters'
    long_name: 'z_position_of_lidar'
    value: 341.0 


parameters:
  # output_block_size: 100
  input:
    path: ..\data\WP5
    format: AQ500
  output:
    path: .\converted
    format: NetCDF4