imports: # read in order
  - ./configs/device.yaml
  - ./configs/scenario.yaml
  - ./configs/metainfo.yaml

parameters:

  data_path: samples/Windscanner/
  input_format: Windscanner
  output_format: NetCDF4