attributes:

  # general instrument description
  lidar_technology: 'pulsed'
  lidar_scanning_type: 'scanning'
  lidar_range_classification: 'long'
  lidar_installation_type: 'ground-based'
  product_name: 'Leosphere WLS-200S'
  lidar_is_mobile: 'false'
  lidar_orientation: 'not applicable'
  flow_direction_encoding: '1'