attributes:

  # general instrument description
  lidar_technology: 'continuous wave'
  lidar_scanning_type: 'vertical profiling'
  lidar_range_classification: 'short'
  lidar_installation_type: 'ground_based'
  product_name: 'ZephIR Z300'
  lidar_is_mobile: 'false'
  lidar_orientation: 'not applicable'
  flow_direction_encoding: 'not applicable'
  n_gates_vary: 'false'
  spatial_averaging_info: ''
  beam_sweeping: 'true'
  measurement_scenario: 'DBS'