attributes:

  # general data set description
  conventions: 'e-WindLidar'
  version: '1.0'
  title: 'Skipheia campaign'
  creator: 'NTNU, Trondheim, Norway'
  references: '-'
  general_comment: 'Lidar - met-mast comparison'
