attributes:

  # general data set description
  conventions: 'e-WindLidar'
  version: '1.0'
  title: '2018 WindyCities'
  creator: 'Stuttgart Wind Energy'
  references: '-'
  general_comment: '###'


