parameters:

  output_block_size: # accepts positive values and <nothing> (in the latter case, produces only one output file)

attributes:

  # measurement configuration
  n_gates_vary: 'false'
  spatial_averaging_info: 'An FFT size of 64 and a the pulse length middle has been used.'
  beam_sweeping: 'true'
  measurement_scenario: 'RHI scan'
  n_lidars: '0'
  linked_lidars: 'not applicable'
  configuration_comment: 'FFT size, pulse length have to be verified.'
